<a href="https://colab.research.google.com/github/PawelAntoniak/Coding/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [42]:
np.zeros(shape=(4,10), dtype='int')


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [48]:
x = np.full(shape=(3,3), fill_value=4, dtype='int')
print(x)

[[4 4 4]
 [4 4 4]
 [4 4 4]]


In [49]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])